adicionando animais para desenhar
opedro/oquecomer pull request #9
Opened 2023-03-09 16:59 UTC by alex3aguiar

2023-03-09 17:24 UTC, g-barbosa requested changes

2023-03-09 17:24 UTC, g-barbosa commented on index.html
> +        <button  alt="Click para decidir o que vai assistir" id="decideAiDesenho">Decide o que eu desenho</button>
Alt do botão de decidir o que desenhar esta igual o de decidir o que assistir

2023-03-09 18:06 UTC, alex3aguiar commented on index.html
> +        <button  alt="Click para decidir o que vai assistir" id="decideAiDesenho">Decide o que eu desenho</button>
arrumei

2023-04-04 20:58 UTC, g-barbosa approved these changes

2023-06-13 23:21 UTC, opedro commented
Não aprovei isso aqui antes de fazer alteração direto na master agora ta com conflito :rindo-de-nervoso:

2023-06-15 02:09 UTC, alex3aguiar commented
> Não aprovei isso aqui antes de fazer alteração direto na master agora ta com conflito :rindo-de-nervoso:

pode deixar que eu arrumo

2023-06-18 14:49 UTC, closed without merging